version: "3"
services:
  pokedex:
    container_name: pokedex
    build:
      context: "./"
      dockerfile: "Dockerfile.pokedex"
    environment:
      - NODE_ENV=development
    volumes:
      - "./:/app"
    command: npm run dev
    restart: unless-stopped
    ports:
      - "3333:3333"
    depends_on:
      - redis
  redis:
    container_name: redis
    image: redis:latest
    restart: unless-stopped
    volumes:
    - "./data/redis:/data"
    ports:
    - "127.0.0.1:6379:6379"
  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"
